### PR TITLE
feat add ns 7 compatibility

### PR DESCRIPTION
**Pull request by Upd4ting**
This pull request make the change for nativescript 7. 
The demo-angular still need to be updated too.

### CODE REVIEW

**Comment by oneiot-tu** [comment]
Hi @Upd4ting,

Thanks a lot for contributing. Could you update the demo app and check that it works for iOS. I would then check for Android 10 and if everything works well will merge the pull request into master.

**Comment by Upd4ting** [comment]
Hi @oneiot-tu,

I'm gonna do that asap once I have some free time in the beginning of the week.

**Comment by Upd4ting** [comment]
Hey @oneiot-tu 

I updated the demo angular application but I'm getting some types errors in your android implementation. Theses types aren't recognized:

```
import NetworkRequest = android.net.NetworkRequest;
import NetworkCapabilities = android.net.NetworkCapabilities;
import WifiNetworkSpecifier = android.net.wifi.WifiNetworkSpecifier;
import Network = android.net.Network;
```

Do you know why? Once that's resolved, I can test ! :)

**Comment by oneiot-tu** [comment]
Do you have the AndroidSDK installed and configured for ns?  The code currently is only working for Android 10 and Android 11. 
If you are only developing for iOS, I could also check for Android if you like.

**Comment by Upd4ting** [comment]
I have the AndroidSDK installed but what do you mean by configured for ns? 
`ns doctor` detect no issues so I thought it was okay.
I will test tomorrow for ios but I would love to be able to test for android too. 

Are you sure for Android 10 and 11 ? I have been using the scan feature on Android 9 and it seems to be working

**Comment by chtinnes** [comment]
When ns doctor is not complaining it should be configured properly, I think. I will have a look again later today.

Regarding the scan feature. This works on Anrdoid 9 but for connecting to an AP, Android 10 functionality is used currently. For Android 9 a solution using and Android 9 API (which I think will also work for Android 8) still needs to be developed. IMHO Android <8 we do not need to support in the future.

**Comment by Upd4ting** [comment]
Nevermind my bad for the android types. I was just wrongly updating `reference.d.ts` for nativescript 7.

I will do some testing on Android et iOS today, I can also switch the connect feature to a lower API.

**Comment by Upd4ting** [comment]
I updated the android code to work with android 8 and I tested it it seems to be working
I'm gonna do some testing on iOS. I won't be able to implement all the features.

**Comment by Upd4ting** [comment]
I've done some fix for iOS. It's working well now!
I only implemented getSSID and connectToWifiNetwork methods. I don't have time to implement more for now, maybe in another PR.
Can you test again and then merge @oneiot-tu ? I need the release for my project.

**Comment by chtinnes** [comment]
Hi, thanks a lot for your efforts. 
I will check in the evening, if the current implementation also works with Android 11.

**Comment by Upd4ting** [comment]
Thanks!

If anything is not working, I can make the required changes, just tell me.

**Comment by chtinnes** [comment]
The code (also the master) seems not to work for Android 11 but i can not see yet why. For some reason, the NetworkCallback is not called. Since this is not due to this PR, we could merge the PR and raise an issue that Android 11 support is missing currently.

**Comment by Upd4ting** [comment]
Thanks for testing! I can take a fast look if you want!
Do you mean that `onAvailable` method from the network callback is never called when we request the network?

**Comment by chtinnes** [comment]
Yes, exactly. `onAvailable` is not called when requesting the network. I just checked again the master for Android 11 and it seems to work. I am now a bit confused, since your code for Android 10 seems to be unchanged.

**Comment by Upd4ting** [comment]
Okay i'm gonna look on my side, if you see what I've done wrong, feel free to tell me.

**Comment by Upd4ting** [comment]
I saw an issue on android < 10, I don't know it's happening in android >= 10.

It seems while I'm connecting to a wifi that has no internet, on some of my device (here a Xiaomi) he connects on the correct wifi during 2-3 seconds then fallback to my home wifi that has internet. Do you maybe know why?

**Comment by chtinnes** [comment]
Yes, this was the reason, why we first implemented it in Android 10. Android < 10 has some issues and the one you describe is one of them. There is already some discussion online on how to workaround this issue. 
For Android > 10 this issue is fixed. I think for Android < 10 you have to force this popup where you can say "stay connected to the wifi".

**Comment by Upd4ting** [comment]
Okay I see. I've been searching the whole day, if you have any idea on how to workaround that correctly you can show me.
I'm still watching what I changed for android 10 with the network callback, but I can't see what I changed.

**Comment by chtinnes** [comment]
Me neither =/. Do you have access to Android 10 / 11 phone to check if it is working for you?
Regarding the Android < 10 issues, I want have time in the next days but we can also raise an issue and fix it later.

**Comment by Upd4ting** [comment]
I have no devices that has Android 10 / 11 :/ 
I can change some stuff if I see the errors but I'll need you to test. Once that's fixed, I think we can merge this PR and do an issue for Android < 10.

**Comment by chtinnes** [comment]
The only major change that I can see is the new ns version. I can try to rollback the version tomorrow to see if this will have any effect.

**Comment by Upd4ting** [comment]
Okay, tell me if that works once you know.

**Comment by chtinnes** [comment]
I known now what causes the issue, since we had the same issue already and it took us hours to debug.

In the tsconfig.json, either `target` or `lib` do cause these issues with some ecmascript versions. 

```
		"target": "es5",
		"lib": [
			"es6",
			"dom",
			"es2015.iterable"
		],
```

**Comment by Upd4ting** [comment]
You mean we need to change `target` and `lib` by the content you just sent? 
Nativescript 7 version require `es2017` as target

**Comment by Upd4ting** [comment]
I am trying to fix the android < 10 issues by also registering network callback. The first time I launched the app, it works, but now my network callback isn't called anymore, do you have any idea?

**Comment by Upd4ting** [comment]
@chtinnes any news?

**Comment by chtinnes** [comment]
Unfortunately, not yet,

I don't find this thing reported somewhere, and it is also really hard to describe. I even don't understand the mechanism.
I just see the symptom that using ES2017, the callback (or something else related to it) is not working. But I have no idea what actually causes it. Do you have any idea how to find the root cause?

**Comment by Upd4ting** [comment]
@chtinnes I don't have any idea currently, but I'm gonna do some testing today

**Comment by Upd4ting** [comment]
I can confirm that if I rollback to nativescript 6.0 `ConnectivityManagerService.NetworkCallback` is called. But once we are in 7.0 with the new `tsconfig.json` the callback aren't called.

That's our main problem because it should fix Android > 10 and should help us to fix the issues we have in Android < 10 with AP that doesn't have internet.

**Comment by Upd4ting** [comment]
@chtinnes I found this interresting issue, could it be related? 
https://github.com/NativeScript/android-runtime/issues/1482

**Comment by chtinnes** [comment]
Yes indeed.
If your linked issue is related to it, there is a little bit more information provided in this issue:  [NativeScript/NativeScript#8455](https://github.com/NativeScript/NativeScript/issues/8455)
Maybe, it is just the `@JavaProxy` annotation that is missing, as described [here](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/extend-application-activity) on how to extend Activities. I will check in the evening.

**Comment by Upd4ting** [comment]
I tried some stuff with `@JavaProxy` but I'm getting `Cannot marshal JavaScript argument () => { } at index 1 to Java type` at class instanciation.
I hope you have more success than me with that.

**Comment by Upd4ting** [comment]
I think that `@JavaProxy` is only used for extending Application and Activity as described in the docs. 
I tried the way of extending as described [here](https://docs.nativescript.org/core-concepts/android-runtime/binding-generator/how-extend-works) but i'm getting `Cannot convert object to Landroid/app/PendingIntent` at `registerNetworkCallback` because the return type of the `extend` method is wrong.
Any idea?

**Comment by Upd4ting** [comment]
The callback should now be okay. Tested on Android < 10 and working. Can you test on Android >= 10 ?
We still have issues with wifi that doesn't have internet. The device switch to a connected internet wifi automatically.
I'll have a look into it as I need it for my work.

**Comment by chtinnes** [comment]
Looks good to me =) 
Can you check one more thing. Can you check the following flow?
connect -> disconnect -> connect again and try to send some data
With the anonymous callback I had some issues regarding the second connect last time I used a similar way to define the callback. If this flow works (for Android >= 10 I will give you feedback in the evening) I think it is finally time to merge the PR =)

**Comment by chtinnes** [comment]
Regarding the unsolicited connection to other WiFis, I would move it to another issue since that is only for Android < 10.
On your device, do you get a popup "Stay connected" when you connect to WiFi with no internet?
I think you need to wait for this. As far as I know, the Android API for < 10 does not support something else. Even for example, when you setup Amazon Alexa, the App tells you that you need to wait for the Popup. This was also recognized by the WiFi API development and they changed the API and provdided new functionality for Anrdoid > 10. I think for android 9 there is also a fix so the problem should only be with Android <=8.

There was also a discussion about this on developer.android.com but I can't find it right now. Will look in the evening (German time) again and keep you updated. 

At least as a workaround, maybe you can try to forget existing networks (and put them later in the list again), if the API allows to do this.

**Comment by Upd4ting** [comment]
Sure I will check the flow you described tomorrow.

Yeah I get a popup "Stay connected" when i'm connecting to WiFi with no internet.
I'm having the problem on Android 9. But I think that the Android version isn't the only thing that determines if the connection will work or not. I have a samsung s7 on Android 8 that is working just fine and a xiaomi on Android 8 that isn't working at all. 
I will probably ask the user to connect manually if I don't find any workaround for that.

I'm okay to move that problem in another issue. 
I will just check your flow to confirm that we can merge this PR.

**Comment by chtinnes** [comment]
With the current approach, the flow is not working for me. As far as I know, when you have an anonymous class, it will be created only once. I.e., the resolve callback will be kind of static in this class and when you call the method again, the new resolve callback isn't used in the networkCallback.  I have no other alternatives yet, the anonymous class has the problem that we can not pass the resolve callback and the other approach does not work at all with es2017. Maybe I will find some way to get the new resolve callback into the networkCallback instance.

Furthermore, the disconnect seems not to work yet (i,e, the callback is also stuck somehow). I will look again into these issues on the weekend.

**Comment by Upd4ting** [comment]
Okay, i'm gonna look into it today and see if I can fix theses issues.

**Comment by chtinnes** [comment]
When you do this already today, here some ideas that I had:

First, you can not put lokal variables into the anonymous class. These are then some kind of runtime static attributes of the anonymous class and not what we want.
Since we can not use subclassing either, you have to give the anonymous class a "real" static variable, e.g., a dispatcher or observable that then forwards to the resolve() calls. Kind of ugly, but the only option I can see right now.

**Comment by Upd4ting** [comment]
@chtinnes I just saw your message. I've done some fix to have the good reference to the resolve. I don't know if that's what you were looking for, but it seems to work. 
About the disconnect, it seems to work correctly but I tested on Android 8/9. Is that an issues only on Android 10/11?

**Comment by Upd4ting** [comment]
I've done a last fix on ios and it's now working really well.

**Comment by Upd4ting** [comment]
I just tested on Android 10 and for me I can connect and disconnect in loop without any issues. Tell me if that works for you too or if there is any others issues.

**Comment by chtinnes** [comment]
Yes it works also for me and also tested on Android 11. Well done! Thanks a lot.
I will merge the PR now to the master branch.

**Comment by Upd4ting** [comment]
No problem. Thanks a lot to you too ! :)

**Pull request merged**
